blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/sosoriov/skills-expand-your-team-with-copilot/discussions
    about: For general questions, ideas, or discussions about the activities system
  - name: 🎯 Quick Help
    url: https://github.com/sosoriov/skills-expand-your-team-with-copilot/wiki
    about: Check the wiki for common questions and troubleshooting guides